apiVersion: apps/v1
kind: Deployment
metadata:
  name: pair-api
  namespace: default
  labels:
    app: pair-api
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: pair-api
  template:
    metadata:
      labels:
        app: pair-api
    spec:
      containers:
      - name: pair-api
        image: docker.io/dk251626910/ffl-pair-api:lastest
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 5"]
        ports:
        - containerPort: 50002
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: pair-api
  namespace: default
spec:
  ports:
    - port: 50002
  selector:
    app: pair-api