// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	element "github.com/acger/pair-api/internal/handler/element"
	"github.com/acger/pair-api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/pair/element/save",
				Handler: element.SaveElementHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pair/element",
				Handler: element.ElementHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pair/element/list",
				Handler: element.ListElementHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/pair/element/pair",
				Handler: pairHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
