Name: pair-api
Host: 0.0.0.0
Port: 50002
Auth:
  AccessSecret: "kkr@kkr@kkr"
  AccessExpire: 7776000
UserSvc:
  Etcd:
    Hosts:
      - dev.ll:2379
    Key: user.rpc
PairSvc:
  Etcd:
    Hosts:
      - dev.ll:2379
    Key: pair.rpc